# -*- coding: utf-8 -*-
"""topo_error_map.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yPLM1oYkKajJc7rPqH1saQYK7y3q5Kvy
"""

import geopandas as gpd
import pandas as pd
import folium
from folium import plugins
import warnings

# Load data
topology_report = pd.read_csv('/content/drive/MyDrive/c.launch/PWD_Parcels_Deliverables/topology_issues_full.csv')
gdf = gpd.read_file('/content/drive/MyDrive/c.launch/PWD_Parcels_Deliverables/PWD_PARCELS.geojson')

# Take top 9500 issues (by area if overlaps, or just first 9500)
top_issues = topology_report.head(9500)

# Get unique parcel indices from the issues
issue_indices = set(top_issues['index_1'].tolist() + top_issues['index_2'].tolist())

# Filter geodataframe to only parcels with issues
gdf_issues = gdf[gdf.index.isin(issue_indices)].copy()

# Reproject to WGS84 for mapping
gdf_issues_map = gdf_issues.to_crs('EPSG:4326')

# Create map (suppress centroid warning - it's fine for map center)
with warnings.catch_warnings():
    warnings.simplefilter("ignore")
    center = [gdf_issues_map.geometry.centroid.y.mean(), gdf_issues_map.geometry.centroid.x.mean()]

m = folium.Map(location=center, zoom_start=11, tiles='CartoDB positron')

# Add parcels with issues
for idx, row in gdf_issues_map.iterrows():
    # Find which issues this parcel is involved in
    parcel_issues = top_issues[(top_issues['index_1'] == idx) | (top_issues['index_2'] == idx)]

    issue_type = parcel_issues['issue_type'].iloc[0] if len(parcel_issues) > 0 else 'unknown'

    # Color by issue type
    if issue_type == 'overlap':
        color = 'red'
    elif issue_type == 'sliver':
        color = 'orange'
    elif issue_type == 'intersection':
        color = 'yellow'
    else:
        color = 'gray'

    folium.GeoJson(
        row['geometry'],
        style_function=lambda x, c=color: {'fillColor': c, 'color': c, 'weight': 1, 'fillOpacity': 0.5},
        tooltip=f"Parcel: {row.get('parcelid', idx)}<br>Issue: {issue_type}"
    ).add_to(m)

# Add legend
legend_html = '''
<div style="position: fixed;
            bottom: 50px; left: 50px; width: 200px; height: auto;
            background-color: white; border:2px solid grey; z-index:9999;
            font-size:14px; padding: 10px; border-radius: 5px;">
<p style="margin:0; font-weight:bold; margin-bottom: 10px;">Topology Issues</p>
<p style="margin:5px 0;"><span style="background-color:red; width:15px; height:15px; display:inline-block; margin-right:5px;"></span> Overlap</p>
<p style="margin:5px 0;"><span style="background-color:orange; width:15px; height:15px; display:inline-block; margin-right:5px;"></span> Sliver</p>
<p style="margin:5px 0;"><span style="background-color:yellow; width:15px; height:15px; display:inline-block; margin-right:5px;"></span> Intersection</p>
<p style="margin-top:10px; font-size:12px; color:gray;">Showing top 9500 of 17,000 issues</p>
</div>
'''
m.get_root().html.add_child(folium.Element(legend_html))

# Save map
m.save('/content/drive/MyDrive/c.launch/PWD_Parcels_Deliverables/topology_issues_map_top9500.html')
print("✓ Map saved: topology_issues_map_top9500.html")
print(f"Total issues mapped: {len(top_issues)}")
print(f"Unique parcels shown: {len(gdf_issues)}")